name: GigaSoftBridge
version: 0.1.0-rc.1
main: com.gigasoft.bridge.paper.GigaBridgePlugin
api-version: '1.21'
authors: [GigaSoft]
commands:
  giga:
    description: Giga runtime controls
    usage: /giga
